/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.onthegomap.planetiler.overture.avrogen;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class categories extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7697914962426791374L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"categories\",\"namespace\":\"com.onthegomap.planetiler.overture.avrogen\",\"fields\":[{\"name\":\"main\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"alternate\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"bag\",\"namespace\":\"bag2\",\"fields\":[{\"name\":\"array_element\",\"type\":[\"null\",\"string\"],\"default\":null}]}}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<categories> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<categories> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<categories> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<categories> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<categories> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this categories to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a categories from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a categories instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static categories fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence main;
  private java.util.List<bag2.bag> alternate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public categories() {}

  /**
   * All-args constructor.
   * @param main The new value for main
   * @param alternate The new value for alternate
   */
  public categories(java.lang.CharSequence main, java.util.List<bag2.bag> alternate) {
    this.main = main;
    this.alternate = alternate;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return main;
    case 1: return alternate;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: main = (java.lang.CharSequence)value$; break;
    case 1: alternate = (java.util.List<bag2.bag>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'main' field.
   * @return The value of the 'main' field.
   */
  public java.lang.CharSequence getMain() {
    return main;
  }


  /**
   * Sets the value of the 'main' field.
   * @param value the value to set.
   */
  public void setMain(java.lang.CharSequence value) {
    this.main = value;
  }

  /**
   * Gets the value of the 'alternate' field.
   * @return The value of the 'alternate' field.
   */
  public java.util.List<bag2.bag> getAlternate() {
    return alternate;
  }


  /**
   * Sets the value of the 'alternate' field.
   * @param value the value to set.
   */
  public void setAlternate(java.util.List<bag2.bag> value) {
    this.alternate = value;
  }

  /**
   * Creates a new categories RecordBuilder.
   * @return A new categories RecordBuilder
   */
  public static com.onthegomap.planetiler.overture.avrogen.categories.Builder newBuilder() {
    return new com.onthegomap.planetiler.overture.avrogen.categories.Builder();
  }

  /**
   * Creates a new categories RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new categories RecordBuilder
   */
  public static com.onthegomap.planetiler.overture.avrogen.categories.Builder newBuilder(com.onthegomap.planetiler.overture.avrogen.categories.Builder other) {
    if (other == null) {
      return new com.onthegomap.planetiler.overture.avrogen.categories.Builder();
    } else {
      return new com.onthegomap.planetiler.overture.avrogen.categories.Builder(other);
    }
  }

  /**
   * Creates a new categories RecordBuilder by copying an existing categories instance.
   * @param other The existing instance to copy.
   * @return A new categories RecordBuilder
   */
  public static com.onthegomap.planetiler.overture.avrogen.categories.Builder newBuilder(com.onthegomap.planetiler.overture.avrogen.categories other) {
    if (other == null) {
      return new com.onthegomap.planetiler.overture.avrogen.categories.Builder();
    } else {
      return new com.onthegomap.planetiler.overture.avrogen.categories.Builder(other);
    }
  }

  /**
   * RecordBuilder for categories instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<categories>
    implements org.apache.avro.data.RecordBuilder<categories> {

    private java.lang.CharSequence main;
    private java.util.List<bag2.bag> alternate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.onthegomap.planetiler.overture.avrogen.categories.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.main)) {
        this.main = data().deepCopy(fields()[0].schema(), other.main);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.alternate)) {
        this.alternate = data().deepCopy(fields()[1].schema(), other.alternate);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing categories instance
     * @param other The existing instance to copy.
     */
    private Builder(com.onthegomap.planetiler.overture.avrogen.categories other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.main)) {
        this.main = data().deepCopy(fields()[0].schema(), other.main);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.alternate)) {
        this.alternate = data().deepCopy(fields()[1].schema(), other.alternate);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'main' field.
      * @return The value.
      */
    public java.lang.CharSequence getMain() {
      return main;
    }


    /**
      * Sets the value of the 'main' field.
      * @param value The value of 'main'.
      * @return This builder.
      */
    public com.onthegomap.planetiler.overture.avrogen.categories.Builder setMain(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.main = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'main' field has been set.
      * @return True if the 'main' field has been set, false otherwise.
      */
    public boolean hasMain() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'main' field.
      * @return This builder.
      */
    public com.onthegomap.planetiler.overture.avrogen.categories.Builder clearMain() {
      main = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'alternate' field.
      * @return The value.
      */
    public java.util.List<bag2.bag> getAlternate() {
      return alternate;
    }


    /**
      * Sets the value of the 'alternate' field.
      * @param value The value of 'alternate'.
      * @return This builder.
      */
    public com.onthegomap.planetiler.overture.avrogen.categories.Builder setAlternate(java.util.List<bag2.bag> value) {
      validate(fields()[1], value);
      this.alternate = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'alternate' field has been set.
      * @return True if the 'alternate' field has been set, false otherwise.
      */
    public boolean hasAlternate() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'alternate' field.
      * @return This builder.
      */
    public com.onthegomap.planetiler.overture.avrogen.categories.Builder clearAlternate() {
      alternate = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public categories build() {
      try {
        categories record = new categories();
        record.main = fieldSetFlags()[0] ? this.main : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.alternate = fieldSetFlags()[1] ? this.alternate : (java.util.List<bag2.bag>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<categories>
    WRITER$ = (org.apache.avro.io.DatumWriter<categories>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<categories>
    READER$ = (org.apache.avro.io.DatumReader<categories>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.main == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.main);
    }

    if (this.alternate == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size0 = this.alternate.size();
      out.writeArrayStart();
      out.setItemCount(size0);
      long actualSize0 = 0;
      for (bag2.bag e0: this.alternate) {
        actualSize0++;
        out.startItem();
        e0.customEncode(out);
      }
      out.writeArrayEnd();
      if (actualSize0 != size0)
        throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.main = null;
      } else {
        this.main = in.readString(this.main instanceof Utf8 ? (Utf8)this.main : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.alternate = null;
      } else {
        long size0 = in.readArrayStart();
        java.util.List<bag2.bag> a0 = this.alternate;
        if (a0 == null) {
          a0 = new SpecificData.Array<bag2.bag>((int)size0, SCHEMA$.getField("alternate").schema().getTypes().get(1));
          this.alternate = a0;
        } else a0.clear();
        SpecificData.Array<bag2.bag> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<bag2.bag>)a0 : null);
        for ( ; 0 < size0; size0 = in.arrayNext()) {
          for ( ; size0 != 0; size0--) {
            bag2.bag e0 = (ga0 != null ? ga0.peek() : null);
            if (e0 == null) {
              e0 = new bag2.bag();
            }
            e0.customDecode(in);
            a0.add(e0);
          }
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.main = null;
          } else {
            this.main = in.readString(this.main instanceof Utf8 ? (Utf8)this.main : null);
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.alternate = null;
          } else {
            long size0 = in.readArrayStart();
            java.util.List<bag2.bag> a0 = this.alternate;
            if (a0 == null) {
              a0 = new SpecificData.Array<bag2.bag>((int)size0, SCHEMA$.getField("alternate").schema().getTypes().get(1));
              this.alternate = a0;
            } else a0.clear();
            SpecificData.Array<bag2.bag> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<bag2.bag>)a0 : null);
            for ( ; 0 < size0; size0 = in.arrayNext()) {
              for ( ; size0 != 0; size0--) {
                bag2.bag e0 = (ga0 != null ? ga0.peek() : null);
                if (e0 == null) {
                  e0 = new bag2.bag();
                }
                e0.customDecode(in);
                a0.add(e0);
              }
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










