/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.onthegomap.planetiler.overture.avrogen;
/** INT96 represented as byte[12] */
@org.apache.avro.specific.FixedSize(12)
@org.apache.avro.specific.AvroGenerated
public class INT96 extends org.apache.avro.specific.SpecificFixed {
  private static final long serialVersionUID = -8872642879444120681L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"fixed\",\"name\":\"INT96\",\"namespace\":\"com.onthegomap.planetiler.overture.avrogen\",\"doc\":\"INT96 represented as byte[12]\",\"size\":12}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  /** Creates a new INT96 */
  public INT96() {
    super();
  }

  /**
   * Creates a new INT96 with the given bytes.
   * @param bytes The bytes to create the new INT96.
   */
  public INT96(byte[] bytes) {
    super(bytes);
  }

  private static final org.apache.avro.io.DatumWriter<INT96>
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter<INT96>(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader<INT96>
    READER$ = new org.apache.avro.specific.SpecificDatumReader<INT96>(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
