{
 "title": "flatmap",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "30s,1m,3m,5m,10m,15m,30m,1h" }
  ]
 },
 "panels": [
  { "title": "Overall progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OSM element progress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flatmap_osm_pass1_elements_processed_total",
     "legendFormat": "pass1 {{type}}"
    },
    {
     "expr": "flatmap_osm_pass2_elements_processed_total",
     "legendFormat": "pass2 {{type}}"
    }
   ]
  },
  {
   "title": "% Progress",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "flatmap_osm_pass2_elements_processed_total\n/\nflatmap_osm_pass1_elements_processed_total",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(flatmap_mbtiles_features_processed_total) / sum(flatmap_renderer_features_emitted_total)",
     "legendFormat": "mbtiles features"
    },
    {
     "expr": "{__name__=~\"^flatmap_.*running$\"}>0",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "What's happening/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(flatmap_osm_pass1_elements_processed_total[$interval])",
     "legendFormat": "pass1 {{type}}"
    },
    {
     "expr": "rate(flatmap_osm_pass2_elements_processed_total[$interval])",
     "legendFormat": "pass2 {{type}}"
    },
    {
     "expr": "rate(flatmap_mbtiles_features_processed_total[$interval])",
     "legendFormat": "mbtiles features processed"
    },
    {
     "expr": "sum(rate(flatmap_renderer_features_emitted_total[$interval])) by (layer)",
     "legendFormat": "pass2 emitted {{layer}} feature"
    },
    {
     "expr": "sum(rate(flatmap_mbtiles_tiles_written_total[$interval])) by (zoom)",
     "legendFormat": "z{{zoom}} tiles written"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{exported_job=\"flatmap\"}[$interval])",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Thread CPU utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_thread_cpu_time_seconds_total[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "GC",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{exported_job=\"flatmap\"}[$interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "File sizes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "flatmap_file_mbtiles_size_bytes",
     "legendFormat": "mbtiles"
    },
    { "expr": "flatmap_file_nodes_size_bytes", "legendFormat": "features" },
    {
     "expr": "flatmap_file_features_size_bytes",
     "legendFormat": "nodes"
    },
    {
     "expr": "flatmap_file_features_usable_space_bytes",
     "legendFormat": "free space"
    }
   ]
  },
  { "title": "pass1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "pass1 PBF reader",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(flatmap_osm_pass1_reader_queue_enqueue_block_time_seconds_total[$interval]))\n/\ncount(jvm_thread_cpu_time_seconds_total{name=~\"^osm_pass1_pbf.*$\"}))",
     "legendFormat": "blocked enqueueing"
    },
    {
     "expr": "avg(rate(jvm_thread_cpu_time_seconds_total{name=~\"^pbfpass1.*$\"}[$interval]))",
     "legendFormat": "PBF reader"
    },
    {
     "expr": "avg(rate(jvm_thread_cpu_time_seconds_total{name=~\"^osm_pass1_pbf.*$\"}[$interval]))* sum(flatmap_osm_pass1_running) > 0",
     "legendFormat": "PBF parsers"
    }
   ]
  },
  {
   "title": "pass1 processor",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flatmap_osm_pass1_reader_queue_dequeue_block_time_seconds_total[$interval]))",
     "legendFormat": "blocked dequeueing"
    },
    {
     "expr": "avg(rate(jvm_thread_cpu_time_seconds_total{name=~\"^osm_pass1_process.*$\"}[$interval]))",
     "legendFormat": "process CPU"
    }
   ]
  },
  {
   "title": "pass1 reader queue",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flatmap_osm_pass1_reader_queue_enqueue_count_total)",
     "legendFormat": "emitted"
    },
    {
     "expr": "sum(flatmap_osm_pass1_reader_queue_enqueue_count_total)",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "pass1 reader queue/sec",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flatmap_osm_pass1_reader_queue_enqueue_count_total[$interval]))",
     "legendFormat": "emitted"
    },
    {
     "expr": "sum(rate(flatmap_osm_pass1_reader_queue_enqueue_count_total[$interval]))",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "pass1 reader queue size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flatmap_osm_pass1_reader_queue_capacity",
     "legendFormat": "capacity"
    },
    {
     "expr": "flatmap_osm_pass1_reader_queue_size",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "reader queue block time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "flatmap_osm_pass1_reader_queue_enqueue_block_time_seconds_total",
     "legendFormat": "enqueue"
    },
    {
     "expr": "flatmap_osm_pass1_reader_queue_dequeue_block_time_seconds_total",
     "legendFormat": "dequeue"
    }
   ]
  },
  { "title": "pass2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "pass2 PBF reader",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(flatmap_osm_pass2_reader_queue_enqueue_block_time_seconds_total[$interval]))\n/\ncount(jvm_thread_cpu_time_seconds_total{name=~\"^osm_pass2_pbf.*$\"}))\n* sum(flatmap_osm_pass2_running) > 0",
     "legendFormat": "blocked enqueueing"
    },
    {
     "expr": "avg(rate(jvm_thread_cpu_time_seconds_total{name=~\"^pbfpass2.*$\"}[$interval])) * sum(flatmap_osm_pass2_running) > 0",
     "legendFormat": "PBF reader"
    },
    {
     "expr": "avg(rate(jvm_thread_cpu_time_seconds_total{name=~\"^osm_pass2_pbf.*$\"}[$interval])) * \nsum(flatmap_osm_pass2_running) > 0",
     "legendFormat": "PBF parsers"
    }
   ]
  },
  {
   "title": "pass2 element processor",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flatmap_osm_pass2_reader_queue_dequeue_block_time_seconds_total[$interval])\n/\nflatmap_osm_pass2_process_threads) * (sum(flatmap_osm_pass2_running) > 0)",
     "legendFormat": "blocked dequeueing"
    },
    {
     "expr": "sum(rate(flatmap_osm_pass2_feature_queue_enqueue_block_time_seconds_total[$interval])\n/\nflatmap_osm_pass2_process_threads) * (sum(flatmap_osm_pass2_running) > 0)",
     "legendFormat": "blocked enqueueing"
    },
    {
     "expr": "sum(avg(rate(jvm_thread_cpu_time_seconds_total{name=~\"^osm_pass2_process.*$\"}[$interval]))) * (sum(flatmap_osm_pass2_running) > 0)",
     "legendFormat": "cpu"
    },
    {
     "expr": "sum(avg(rate(jvm_thread_user_time_seconds_total{name=~\"^osm_pass2_process.*$\"}[$interval]))) * (sum(flatmap_osm_pass2_running) > 0)",
     "legendFormat": "user time"
    }
   ]
  },
  {
   "title": "pass2 writer",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flatmap_osm_pass2_feature_queue_dequeue_block_time_seconds_total[$interval])\n/\nflatmap_osm_pass2_write_threads) * (sum(flatmap_osm_pass2_running) > 0)",
     "legendFormat": "blocked dequeueing"
    },
    {
     "expr": "avg(rate(jvm_thread_cpu_time_seconds_total{name=~\"^osm_pass2_write.*$\"}[$interval])) * (sum(flatmap_osm_pass2_running) > 0)",
     "legendFormat": "cpu"
    },
    {
     "expr": "avg(rate(jvm_thread_user_time_seconds_total{name=~\"^osm_pass2_write.*$\"}[$interval])) * (sum(flatmap_osm_pass2_running) > 0)",
     "legendFormat": "user time"
    }
   ]
  },
  {
   "title": "pass2 reader queue",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flatmap_osm_pass2_reader_queue_enqueue_count_total)",
     "legendFormat": "emitted"
    },
    {
     "expr": "sum(flatmap_osm_pass2_reader_queue_dequeue_count_total)",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "pass2 reader features/sec",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flatmap_osm_pass2_reader_queue_enqueue_count_total[$interval]))",
     "legendFormat": "emitted"
    },
    {
     "expr": "sum(rate(flatmap_osm_pass2_reader_queue_dequeue_count_total[$interval]))",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "pass2 reader queue size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flatmap_osm_pass2_reader_queue_capacity",
     "legendFormat": "capacity"
    },
    {
     "expr": "flatmap_osm_pass2_reader_queue_size",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "reader queue block time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "flatmap_osm_pass2_reader_queue_enqueue_block_time_seconds_total",
     "legendFormat": "enqueue"
    },
    {
     "expr": "flatmap_osm_pass2_reader_queue_dequeue_block_time_seconds_total",
     "legendFormat": "dequeue"
    }
   ]
  },
  {
   "title": "pass2 writer queue count",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flatmap_osm_pass2_feature_queue_enqueue_count_total)",
     "legendFormat": "emitted"
    },
    {
     "expr": "sum(flatmap_osm_pass2_feature_queue_dequeue_count_total)",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "pass2 writer queue/sec",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flatmap_osm_pass2_feature_queue_enqueue_count_total[$interval]))",
     "legendFormat": "emitted"
    },
    {
     "expr": "sum(rate(flatmap_osm_pass2_feature_queue_dequeue_count_total[$interval]))",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "pass2 writer queue size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flatmap_osm_pass2_feature_queue_capacity",
     "legendFormat": "capacity"
    },
    {
     "expr": "flatmap_osm_pass2_feature_queue_size",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "writer queue block time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "flatmap_osm_pass2_feature_queue_enqueue_block_time_seconds_total",
     "legendFormat": "enqueue"
    },
    {
     "expr": "flatmap_osm_pass2_feature_queue_dequeue_block_time_seconds_total",
     "legendFormat": "dequeue"
    }
   ]
  },
  { "title": "mbtiles writer pass", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "mbtiles encoder",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(flatmap_mbtiles_writer_queue_enqueue_block_time_seconds_total[$interval])\n/\nflatmap_mbtiles_encoder_threads",
     "legendFormat": "blocked enqueueing"
    },
    {
     "expr": "avg(rate(jvm_thread_cpu_time_seconds_total{name=~\"^mbtiles_encoder.*$\"}[$interval]))",
     "legendFormat": "cpu"
    },
    {
     "expr": "avg(rate(jvm_thread_user_time_seconds_total{name=~\"^mbtiles_encoder.*$\"}[$interval]))",
     "legendFormat": "user time"
    }
   ]
  },
  {
   "title": "mbtiles writer",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(flatmap_mbtiles_writer_queue_dequeue_block_time_seconds_total[$interval])\n/\nflatmap_mbtiles_writer_threads",
     "legendFormat": "blocked dequeueing"
    },
    {
     "expr": "avg(rate(jvm_thread_cpu_time_seconds_total{name=~\"^mbtiles_writer.*$\"}[$interval]))",
     "legendFormat": "cpu"
    },
    {
     "expr": "avg(rate(jvm_thread_user_time_seconds_total{name=~\"^mbtiles_writer.*$\"}[$interval]))",
     "legendFormat": "user time"
    }
   ]
  },
  {
   "title": "mbtiles features",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(flatmap_mbtiles_reader_queue_enqueue_count_total)",
     "legendFormat": "emitted"
    },
    {
     "expr": "sum(flatmap_mbtiles_reader_queue_dequeue_count_total)",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "mbtiles features/sec",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(flatmap_mbtiles_reader_queue_enqueue_count_total[$interval]))",
     "legendFormat": "emitted"
    },
    {
     "expr": "sum(rate(flatmap_mbtiles_reader_queue_dequeue_count_total[$interval]))",
     "legendFormat": "processed"
    }
   ]
  },
  {
   "title": "mbtiles queue size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flatmap_mbtiles_reader_queue_capacity",
     "legendFormat": "capacity"
    },
    {
     "expr": "flatmap_mbtiles_reader_queue_size",
     "legendFormat": "size"
    }
   ]
  },
  {
   "title": "mbtiles queue block time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "flatmap_mbtiles_reader_queue_enqueue_block_time_seconds_total",
     "legendFormat": "enqueue"
    },
    {
     "expr": "flatmap_mbtiles_reader_queue_dequeue_block_time_seconds_total",
     "legendFormat": "dequeue"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{exported_job=\"flatmap\"}",
     "legendFormat": "{{area}}",
     "override": { "fill": 0 }
    }
   ]
  },
  {
   "title": "memory pools",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{exported_job=\"flatmap\"}",
     "legendFormat": "{{pool}}",
     "override": { "fill": 0 }
    },
    {
     "expr": "jvm_buffer_pool_used_bytes{exported_job=\"flatmap\"}",
     "legendFormat": "{{pool}} buffer pool",
     "override": { "fill": 0 }
    }
   ]
  },
  {
   "title": "% time in GC",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{exported_job=\"flatmap\"}[$interval])) by (instance_alias, job)",
     "legendFormat": "{{instance_alias}} {{job}}"
    }
   ]
  },
  {
   "title": "gc count per $interval",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{exported_job=\"flatmap\"}[$interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{exported_job=\"flatmap\"}",
     "legendFormat": "{{instance_alias}} {{job}}"
    }
   ]
  },
  {
   "title": "threads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{exported_job=\"flatmap\"}"
    }
   ]
  }
 ]
}