// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: planetiler-core/src/main/resources/fileformat.proto

package crosby.binary;

@javax.annotation.Generated(value = "protoc", comments = "annotations:Fileformat.java.pb.meta")
public final class Fileformat {
  private Fileformat() {}

  public static void registerAllExtensions(
    com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(
    com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
      (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface BlobOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OSMPBF.Blob)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * When compressed, the uncompressed size
     * </pre>
     *
     * <code>optional int32 raw_size = 2;</code>
     * 
     * @return Whether the rawSize field is set.
     */
    boolean hasRawSize();

    /**
     * <pre>
     * When compressed, the uncompressed size
     * </pre>
     *
     * <code>optional int32 raw_size = 2;</code>
     * 
     * @return The rawSize.
     */
    int getRawSize();

    /**
     * <pre>
     * No compression
     * </pre>
     *
     * <code>bytes raw = 1;</code>
     * 
     * @return Whether the raw field is set.
     */
    boolean hasRaw();

    /**
     * <pre>
     * No compression
     * </pre>
     *
     * <code>bytes raw = 1;</code>
     * 
     * @return The raw.
     */
    com.google.protobuf.ByteString getRaw();

    /**
     * <pre>
     * Possible compressed versions of the data.
     * </pre>
     *
     * <code>bytes zlib_data = 3;</code>
     * 
     * @return Whether the zlibData field is set.
     */
    boolean hasZlibData();

    /**
     * <pre>
     * Possible compressed versions of the data.
     * </pre>
     *
     * <code>bytes zlib_data = 3;</code>
     * 
     * @return The zlibData.
     */
    com.google.protobuf.ByteString getZlibData();

    /**
     * <pre>
     * For LZMA compressed data (optional)
     * </pre>
     *
     * <code>bytes lzma_data = 4;</code>
     * 
     * @return Whether the lzmaData field is set.
     */
    boolean hasLzmaData();

    /**
     * <pre>
     * For LZMA compressed data (optional)
     * </pre>
     *
     * <code>bytes lzma_data = 4;</code>
     * 
     * @return The lzmaData.
     */
    com.google.protobuf.ByteString getLzmaData();

    /**
     * <pre>
     * Formerly used for bzip2 compressed data. Deprecated in 2010.
     * </pre>
     *
     * <code>bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
     * 
     * @return Whether the oBSOLETEBzip2Data field is set.
     */
    @java.lang.Deprecated
    boolean hasOBSOLETEBzip2Data();

    /**
     * <pre>
     * Formerly used for bzip2 compressed data. Deprecated in 2010.
     * </pre>
     *
     * <code>bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
     * 
     * @return The oBSOLETEBzip2Data.
     */
    @java.lang.Deprecated
    com.google.protobuf.ByteString getOBSOLETEBzip2Data();

    /**
     * <pre>
     * For LZ4 compressed data (optional)
     * </pre>
     *
     * <code>bytes lz4_data = 6;</code>
     * 
     * @return Whether the lz4Data field is set.
     */
    boolean hasLz4Data();

    /**
     * <pre>
     * For LZ4 compressed data (optional)
     * </pre>
     *
     * <code>bytes lz4_data = 6;</code>
     * 
     * @return The lz4Data.
     */
    com.google.protobuf.ByteString getLz4Data();

    /**
     * <pre>
     * For ZSTD compressed data (optional)
     * </pre>
     *
     * <code>bytes zstd_data = 7;</code>
     * 
     * @return Whether the zstdData field is set.
     */
    boolean hasZstdData();

    /**
     * <pre>
     * For ZSTD compressed data (optional)
     * </pre>
     *
     * <code>bytes zstd_data = 7;</code>
     * 
     * @return The zstdData.
     */
    com.google.protobuf.ByteString getZstdData();

    public crosby.binary.Fileformat.Blob.DataCase getDataCase();
  }
  /**
   * Protobuf type {@code OSMPBF.Blob}
   */
  public static final class Blob extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:OSMPBF.Blob)
    BlobOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use Blob.newBuilder() to construct.
    private Blob(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Blob() {}

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
      return new Blob();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private Blob(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              dataCase_ = 1;
              data_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              rawSize_ = input.readInt32();
              break;
            }
            case 26: {
              dataCase_ = 3;
              data_ = input.readBytes();
              break;
            }
            case 34: {
              dataCase_ = 4;
              data_ = input.readBytes();
              break;
            }
            case 42: {
              dataCase_ = 5;
              data_ = input.readBytes();
              break;
            }
            case 50: {
              dataCase_ = 6;
              data_ = input.readBytes();
              break;
            }
            case 58: {
              dataCase_ = 7;
              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return crosby.binary.Fileformat.internal_static_OSMPBF_Blob_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return crosby.binary.Fileformat.internal_static_OSMPBF_Blob_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
          crosby.binary.Fileformat.Blob.class, crosby.binary.Fileformat.Blob.Builder.class);
    }

    private int bitField0_;
    private int dataCase_ = 0;
    private java.lang.Object data_;

    public enum DataCase
      implements com.google.protobuf.Internal.EnumLite,
      com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      RAW(1),
      ZLIB_DATA(3),
      LZMA_DATA(4),
      @java.lang.Deprecated
      OBSOLETE_BZIP2_DATA(5),
      LZ4_DATA(6),
      ZSTD_DATA(7),
      DATA_NOT_SET(0);

      private final int value;

      private DataCase(int value) {
        this.value = value;
      }

      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataCase forNumber(int value) {
        switch (value) {
          case 1:
            return RAW;
          case 3:
            return ZLIB_DATA;
          case 4:
            return LZMA_DATA;
          case 5:
            return OBSOLETE_BZIP2_DATA;
          case 6:
            return LZ4_DATA;
          case 7:
            return ZSTD_DATA;
          case 0:
            return DATA_NOT_SET;
          default:
            return null;
        }
      }

      public int getNumber() {
        return this.value;
      }
    };

    public DataCase getDataCase() {
      return DataCase.forNumber(
        dataCase_);
    }

    public static final int RAW_SIZE_FIELD_NUMBER = 2;
    private int rawSize_;

    /**
     * <pre>
     * When compressed, the uncompressed size
     * </pre>
     *
     * <code>optional int32 raw_size = 2;</code>
     * 
     * @return Whether the rawSize field is set.
     */
    @java.lang.Override
    public boolean hasRawSize() {
      return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <pre>
     * When compressed, the uncompressed size
     * </pre>
     *
     * <code>optional int32 raw_size = 2;</code>
     * 
     * @return The rawSize.
     */
    @java.lang.Override
    public int getRawSize() {
      return rawSize_;
    }

    public static final int RAW_FIELD_NUMBER = 1;

    /**
     * <pre>
     * No compression
     * </pre>
     *
     * <code>bytes raw = 1;</code>
     * 
     * @return Whether the raw field is set.
     */
    @java.lang.Override
    public boolean hasRaw() {
      return dataCase_ == 1;
    }

    /**
     * <pre>
     * No compression
     * </pre>
     *
     * <code>bytes raw = 1;</code>
     * 
     * @return The raw.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRaw() {
      if (dataCase_ == 1) {
        return (com.google.protobuf.ByteString) data_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    public static final int ZLIB_DATA_FIELD_NUMBER = 3;

    /**
     * <pre>
     * Possible compressed versions of the data.
     * </pre>
     *
     * <code>bytes zlib_data = 3;</code>
     * 
     * @return Whether the zlibData field is set.
     */
    @java.lang.Override
    public boolean hasZlibData() {
      return dataCase_ == 3;
    }

    /**
     * <pre>
     * Possible compressed versions of the data.
     * </pre>
     *
     * <code>bytes zlib_data = 3;</code>
     * 
     * @return The zlibData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getZlibData() {
      if (dataCase_ == 3) {
        return (com.google.protobuf.ByteString) data_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    public static final int LZMA_DATA_FIELD_NUMBER = 4;

    /**
     * <pre>
     * For LZMA compressed data (optional)
     * </pre>
     *
     * <code>bytes lzma_data = 4;</code>
     * 
     * @return Whether the lzmaData field is set.
     */
    @java.lang.Override
    public boolean hasLzmaData() {
      return dataCase_ == 4;
    }

    /**
     * <pre>
     * For LZMA compressed data (optional)
     * </pre>
     *
     * <code>bytes lzma_data = 4;</code>
     * 
     * @return The lzmaData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLzmaData() {
      if (dataCase_ == 4) {
        return (com.google.protobuf.ByteString) data_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    public static final int OBSOLETE_BZIP2_DATA_FIELD_NUMBER = 5;

    /**
     * <pre>
     * Formerly used for bzip2 compressed data. Deprecated in 2010.
     * </pre>
     *
     * <code>bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
     * 
     * @return Whether the oBSOLETEBzip2Data field is set.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public boolean hasOBSOLETEBzip2Data() {
      return dataCase_ == 5;
    }

    /**
     * <pre>
     * Formerly used for bzip2 compressed data. Deprecated in 2010.
     * </pre>
     *
     * <code>bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
     * 
     * @return The oBSOLETEBzip2Data.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public com.google.protobuf.ByteString getOBSOLETEBzip2Data() {
      if (dataCase_ == 5) {
        return (com.google.protobuf.ByteString) data_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    public static final int LZ4_DATA_FIELD_NUMBER = 6;

    /**
     * <pre>
     * For LZ4 compressed data (optional)
     * </pre>
     *
     * <code>bytes lz4_data = 6;</code>
     * 
     * @return Whether the lz4Data field is set.
     */
    @java.lang.Override
    public boolean hasLz4Data() {
      return dataCase_ == 6;
    }

    /**
     * <pre>
     * For LZ4 compressed data (optional)
     * </pre>
     *
     * <code>bytes lz4_data = 6;</code>
     * 
     * @return The lz4Data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getLz4Data() {
      if (dataCase_ == 6) {
        return (com.google.protobuf.ByteString) data_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    public static final int ZSTD_DATA_FIELD_NUMBER = 7;

    /**
     * <pre>
     * For ZSTD compressed data (optional)
     * </pre>
     *
     * <code>bytes zstd_data = 7;</code>
     * 
     * @return Whether the zstdData field is set.
     */
    @java.lang.Override
    public boolean hasZstdData() {
      return dataCase_ == 7;
    }

    /**
     * <pre>
     * For ZSTD compressed data (optional)
     * </pre>
     *
     * <code>bytes zstd_data = 7;</code>
     * 
     * @return The zstdData.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getZstdData() {
      if (dataCase_ == 7) {
        return (com.google.protobuf.ByteString) data_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
      if (dataCase_ == 1) {
        output.writeBytes(
          1, (com.google.protobuf.ByteString) data_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(2, rawSize_);
      }
      if (dataCase_ == 3) {
        output.writeBytes(
          3, (com.google.protobuf.ByteString) data_);
      }
      if (dataCase_ == 4) {
        output.writeBytes(
          4, (com.google.protobuf.ByteString) data_);
      }
      if (dataCase_ == 5) {
        output.writeBytes(
          5, (com.google.protobuf.ByteString) data_);
      }
      if (dataCase_ == 6) {
        output.writeBytes(
          6, (com.google.protobuf.ByteString) data_);
      }
      if (dataCase_ == 7) {
        output.writeBytes(
          7, (com.google.protobuf.ByteString) data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1)
        return size;

      size = 0;
      if (dataCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
            1, (com.google.protobuf.ByteString) data_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, rawSize_);
      }
      if (dataCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
            3, (com.google.protobuf.ByteString) data_);
      }
      if (dataCase_ == 4) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
            4, (com.google.protobuf.ByteString) data_);
      }
      if (dataCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
            5, (com.google.protobuf.ByteString) data_);
      }
      if (dataCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
            6, (com.google.protobuf.ByteString) data_);
      }
      if (dataCase_ == 7) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
            7, (com.google.protobuf.ByteString) data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof crosby.binary.Fileformat.Blob)) {
        return super.equals(obj);
      }
      crosby.binary.Fileformat.Blob other = (crosby.binary.Fileformat.Blob) obj;

      if (hasRawSize() != other.hasRawSize())
        return false;
      if (hasRawSize()) {
        if (getRawSize() != other.getRawSize())
          return false;
      }
      if (!getDataCase().equals(other.getDataCase()))
        return false;
      switch (dataCase_) {
        case 1:
          if (!getRaw()
            .equals(other.getRaw()))
            return false;
          break;
        case 3:
          if (!getZlibData()
            .equals(other.getZlibData()))
            return false;
          break;
        case 4:
          if (!getLzmaData()
            .equals(other.getLzmaData()))
            return false;
          break;
        case 5:
          if (!getOBSOLETEBzip2Data()
            .equals(other.getOBSOLETEBzip2Data()))
            return false;
          break;
        case 6:
          if (!getLz4Data()
            .equals(other.getLz4Data()))
            return false;
          break;
        case 7:
          if (!getZstdData()
            .equals(other.getZstdData()))
            return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields))
        return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRawSize()) {
        hash = (37 * hash) + RAW_SIZE_FIELD_NUMBER;
        hash = (53 * hash) + getRawSize();
      }
      switch (dataCase_) {
        case 1:
          hash = (37 * hash) + RAW_FIELD_NUMBER;
          hash = (53 * hash) + getRaw().hashCode();
          break;
        case 3:
          hash = (37 * hash) + ZLIB_DATA_FIELD_NUMBER;
          hash = (53 * hash) + getZlibData().hashCode();
          break;
        case 4:
          hash = (37 * hash) + LZMA_DATA_FIELD_NUMBER;
          hash = (53 * hash) + getLzmaData().hashCode();
          break;
        case 5:
          hash = (37 * hash) + OBSOLETE_BZIP2_DATA_FIELD_NUMBER;
          hash = (53 * hash) + getOBSOLETEBzip2Data().hashCode();
          break;
        case 6:
          hash = (37 * hash) + LZ4_DATA_FIELD_NUMBER;
          hash = (53 * hash) + getLz4Data().hashCode();
          break;
        case 7:
          hash = (37 * hash) + ZSTD_DATA_FIELD_NUMBER;
          hash = (53 * hash) + getZstdData().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static crosby.binary.Fileformat.Blob parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static crosby.binary.Fileformat.Blob parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static crosby.binary.Fileformat.Blob parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static crosby.binary.Fileformat.Blob parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static crosby.binary.Fileformat.Blob parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static crosby.binary.Fileformat.Blob parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static crosby.binary.Fileformat.Blob parseFrom(java.io.InputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
    }

    public static crosby.binary.Fileformat.Blob parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static crosby.binary.Fileformat.Blob parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
    }

    public static crosby.binary.Fileformat.Blob parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static crosby.binary.Fileformat.Blob parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
    }

    public static crosby.binary.Fileformat.Blob parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(crosby.binary.Fileformat.Blob prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code OSMPBF.Blob}
     */
    public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OSMPBF.Blob)
      crosby.binary.Fileformat.BlobOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return crosby.binary.Fileformat.internal_static_OSMPBF_Blob_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return crosby.binary.Fileformat.internal_static_OSMPBF_Blob_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
            crosby.binary.Fileformat.Blob.class, crosby.binary.Fileformat.Blob.Builder.class);
      }

      // Construct using crosby.binary.Fileformat.Blob.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        rawSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        dataCase_ = 0;
        data_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return crosby.binary.Fileformat.internal_static_OSMPBF_Blob_descriptor;
      }

      @java.lang.Override
      public crosby.binary.Fileformat.Blob getDefaultInstanceForType() {
        return crosby.binary.Fileformat.Blob.getDefaultInstance();
      }

      @java.lang.Override
      public crosby.binary.Fileformat.Blob build() {
        crosby.binary.Fileformat.Blob result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public crosby.binary.Fileformat.Blob buildPartial() {
        crosby.binary.Fileformat.Blob result = new crosby.binary.Fileformat.Blob(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.rawSize_ = rawSize_;
          to_bitField0_ |= 0x00000001;
        }
        if (dataCase_ == 1) {
          result.data_ = data_;
        }
        if (dataCase_ == 3) {
          result.data_ = data_;
        }
        if (dataCase_ == 4) {
          result.data_ = data_;
        }
        if (dataCase_ == 5) {
          result.data_ = data_;
        }
        if (dataCase_ == 6) {
          result.data_ = data_;
        }
        if (dataCase_ == 7) {
          result.data_ = data_;
        }
        result.bitField0_ = to_bitField0_;
        result.dataCase_ = dataCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof crosby.binary.Fileformat.Blob) {
          return mergeFrom((crosby.binary.Fileformat.Blob) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(crosby.binary.Fileformat.Blob other) {
        if (other == crosby.binary.Fileformat.Blob.getDefaultInstance())
          return this;
        if (other.hasRawSize()) {
          setRawSize(other.getRawSize());
        }
        switch (other.getDataCase()) {
          case RAW: {
            setRaw(other.getRaw());
            break;
          }
          case ZLIB_DATA: {
            setZlibData(other.getZlibData());
            break;
          }
          case LZMA_DATA: {
            setLzmaData(other.getLzmaData());
            break;
          }
          case OBSOLETE_BZIP2_DATA: {
            setOBSOLETEBzip2Data(other.getOBSOLETEBzip2Data());
            break;
          }
          case LZ4_DATA: {
            setLz4Data(other.getLz4Data());
            break;
          }
          case ZSTD_DATA: {
            setZstdData(other.getZstdData());
            break;
          }
          case DATA_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        crosby.binary.Fileformat.Blob parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (crosby.binary.Fileformat.Blob) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int dataCase_ = 0;
      private java.lang.Object data_;

      public DataCase getDataCase() {
        return DataCase.forNumber(
          dataCase_);
      }

      public Builder clearData() {
        dataCase_ = 0;
        data_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int rawSize_;

      /**
       * <pre>
       * When compressed, the uncompressed size
       * </pre>
       *
       * <code>optional int32 raw_size = 2;</code>
       * 
       * @return Whether the rawSize field is set.
       */
      @java.lang.Override
      public boolean hasRawSize() {
        return ((bitField0_ & 0x00000001) != 0);
      }

      /**
       * <pre>
       * When compressed, the uncompressed size
       * </pre>
       *
       * <code>optional int32 raw_size = 2;</code>
       * 
       * @return The rawSize.
       */
      @java.lang.Override
      public int getRawSize() {
        return rawSize_;
      }

      /**
       * <pre>
       * When compressed, the uncompressed size
       * </pre>
       *
       * <code>optional int32 raw_size = 2;</code>
       * 
       * @param value The rawSize to set.
       * @return This builder for chaining.
       */
      public Builder setRawSize(int value) {
        bitField0_ |= 0x00000001;
        rawSize_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * When compressed, the uncompressed size
       * </pre>
       *
       * <code>optional int32 raw_size = 2;</code>
       * 
       * @return This builder for chaining.
       */
      public Builder clearRawSize() {
        bitField0_ = (bitField0_ & ~0x00000001);
        rawSize_ = 0;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * No compression
       * </pre>
       *
       * <code>bytes raw = 1;</code>
       * 
       * @return Whether the raw field is set.
       */
      public boolean hasRaw() {
        return dataCase_ == 1;
      }

      /**
       * <pre>
       * No compression
       * </pre>
       *
       * <code>bytes raw = 1;</code>
       * 
       * @return The raw.
       */
      public com.google.protobuf.ByteString getRaw() {
        if (dataCase_ == 1) {
          return (com.google.protobuf.ByteString) data_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }

      /**
       * <pre>
       * No compression
       * </pre>
       *
       * <code>bytes raw = 1;</code>
       * 
       * @param value The raw to set.
       * @return This builder for chaining.
       */
      public Builder setRaw(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataCase_ = 1;
        data_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * No compression
       * </pre>
       *
       * <code>bytes raw = 1;</code>
       * 
       * @return This builder for chaining.
       */
      public Builder clearRaw() {
        if (dataCase_ == 1) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <pre>
       * Possible compressed versions of the data.
       * </pre>
       *
       * <code>bytes zlib_data = 3;</code>
       * 
       * @return Whether the zlibData field is set.
       */
      public boolean hasZlibData() {
        return dataCase_ == 3;
      }

      /**
       * <pre>
       * Possible compressed versions of the data.
       * </pre>
       *
       * <code>bytes zlib_data = 3;</code>
       * 
       * @return The zlibData.
       */
      public com.google.protobuf.ByteString getZlibData() {
        if (dataCase_ == 3) {
          return (com.google.protobuf.ByteString) data_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }

      /**
       * <pre>
       * Possible compressed versions of the data.
       * </pre>
       *
       * <code>bytes zlib_data = 3;</code>
       * 
       * @param value The zlibData to set.
       * @return This builder for chaining.
       */
      public Builder setZlibData(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataCase_ = 3;
        data_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * Possible compressed versions of the data.
       * </pre>
       *
       * <code>bytes zlib_data = 3;</code>
       * 
       * @return This builder for chaining.
       */
      public Builder clearZlibData() {
        if (dataCase_ == 3) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <pre>
       * For LZMA compressed data (optional)
       * </pre>
       *
       * <code>bytes lzma_data = 4;</code>
       * 
       * @return Whether the lzmaData field is set.
       */
      public boolean hasLzmaData() {
        return dataCase_ == 4;
      }

      /**
       * <pre>
       * For LZMA compressed data (optional)
       * </pre>
       *
       * <code>bytes lzma_data = 4;</code>
       * 
       * @return The lzmaData.
       */
      public com.google.protobuf.ByteString getLzmaData() {
        if (dataCase_ == 4) {
          return (com.google.protobuf.ByteString) data_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }

      /**
       * <pre>
       * For LZMA compressed data (optional)
       * </pre>
       *
       * <code>bytes lzma_data = 4;</code>
       * 
       * @param value The lzmaData to set.
       * @return This builder for chaining.
       */
      public Builder setLzmaData(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataCase_ = 4;
        data_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * For LZMA compressed data (optional)
       * </pre>
       *
       * <code>bytes lzma_data = 4;</code>
       * 
       * @return This builder for chaining.
       */
      public Builder clearLzmaData() {
        if (dataCase_ == 4) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <pre>
       * Formerly used for bzip2 compressed data. Deprecated in 2010.
       * </pre>
       *
       * <code>bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
       * 
       * @return Whether the oBSOLETEBzip2Data field is set.
       */
      @java.lang.Deprecated
      public boolean hasOBSOLETEBzip2Data() {
        return dataCase_ == 5;
      }

      /**
       * <pre>
       * Formerly used for bzip2 compressed data. Deprecated in 2010.
       * </pre>
       *
       * <code>bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
       * 
       * @return The oBSOLETEBzip2Data.
       */
      @java.lang.Deprecated
      public com.google.protobuf.ByteString getOBSOLETEBzip2Data() {
        if (dataCase_ == 5) {
          return (com.google.protobuf.ByteString) data_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }

      /**
       * <pre>
       * Formerly used for bzip2 compressed data. Deprecated in 2010.
       * </pre>
       *
       * <code>bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
       * 
       * @param value The oBSOLETEBzip2Data to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated
      public Builder setOBSOLETEBzip2Data(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataCase_ = 5;
        data_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * Formerly used for bzip2 compressed data. Deprecated in 2010.
       * </pre>
       *
       * <code>bytes OBSOLETE_bzip2_data = 5 [deprecated = true];</code>
       * 
       * @return This builder for chaining.
       */
      @java.lang.Deprecated
      public Builder clearOBSOLETEBzip2Data() {
        if (dataCase_ == 5) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <pre>
       * For LZ4 compressed data (optional)
       * </pre>
       *
       * <code>bytes lz4_data = 6;</code>
       * 
       * @return Whether the lz4Data field is set.
       */
      public boolean hasLz4Data() {
        return dataCase_ == 6;
      }

      /**
       * <pre>
       * For LZ4 compressed data (optional)
       * </pre>
       *
       * <code>bytes lz4_data = 6;</code>
       * 
       * @return The lz4Data.
       */
      public com.google.protobuf.ByteString getLz4Data() {
        if (dataCase_ == 6) {
          return (com.google.protobuf.ByteString) data_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }

      /**
       * <pre>
       * For LZ4 compressed data (optional)
       * </pre>
       *
       * <code>bytes lz4_data = 6;</code>
       * 
       * @param value The lz4Data to set.
       * @return This builder for chaining.
       */
      public Builder setLz4Data(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataCase_ = 6;
        data_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * For LZ4 compressed data (optional)
       * </pre>
       *
       * <code>bytes lz4_data = 6;</code>
       * 
       * @return This builder for chaining.
       */
      public Builder clearLz4Data() {
        if (dataCase_ == 6) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <pre>
       * For ZSTD compressed data (optional)
       * </pre>
       *
       * <code>bytes zstd_data = 7;</code>
       * 
       * @return Whether the zstdData field is set.
       */
      public boolean hasZstdData() {
        return dataCase_ == 7;
      }

      /**
       * <pre>
       * For ZSTD compressed data (optional)
       * </pre>
       *
       * <code>bytes zstd_data = 7;</code>
       * 
       * @return The zstdData.
       */
      public com.google.protobuf.ByteString getZstdData() {
        if (dataCase_ == 7) {
          return (com.google.protobuf.ByteString) data_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }

      /**
       * <pre>
       * For ZSTD compressed data (optional)
       * </pre>
       *
       * <code>bytes zstd_data = 7;</code>
       * 
       * @param value The zstdData to set.
       * @return This builder for chaining.
       */
      public Builder setZstdData(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        dataCase_ = 7;
        data_ = value;
        onChanged();
        return this;
      }

      /**
       * <pre>
       * For ZSTD compressed data (optional)
       * </pre>
       *
       * <code>bytes zstd_data = 7;</code>
       * 
       * @return This builder for chaining.
       */
      public Builder clearZstdData() {
        if (dataCase_ == 7) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OSMPBF.Blob)
    }

    // @@protoc_insertion_point(class_scope:OSMPBF.Blob)
    private static final crosby.binary.Fileformat.Blob DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new crosby.binary.Fileformat.Blob();
    }

    public static crosby.binary.Fileformat.Blob getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated
    public static final com.google.protobuf.Parser<Blob> PARSER = new com.google.protobuf.AbstractParser<Blob>() {
      @java.lang.Override
      public Blob parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Blob(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Blob> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Blob> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public crosby.binary.Fileformat.Blob getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BlobHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OSMPBF.BlobHeader)
    com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string type = 1;</code>
     * 
     * @return Whether the type field is set.
     */
    boolean hasType();

    /**
     * <code>required string type = 1;</code>
     * 
     * @return The type.
     */
    java.lang.String getType();

    /**
     * <code>required string type = 1;</code>
     * 
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString getTypeBytes();

    /**
     * <code>optional bytes indexdata = 2;</code>
     * 
     * @return Whether the indexdata field is set.
     */
    boolean hasIndexdata();

    /**
     * <code>optional bytes indexdata = 2;</code>
     * 
     * @return The indexdata.
     */
    com.google.protobuf.ByteString getIndexdata();

    /**
     * <code>required int32 datasize = 3;</code>
     * 
     * @return Whether the datasize field is set.
     */
    boolean hasDatasize();

    /**
     * <code>required int32 datasize = 3;</code>
     * 
     * @return The datasize.
     */
    int getDatasize();
  }
  /**
   * Protobuf type {@code OSMPBF.BlobHeader}
   */
  public static final class BlobHeader extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:OSMPBF.BlobHeader)
    BlobHeaderOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use BlobHeader.newBuilder() to construct.
    private BlobHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private BlobHeader() {
      type_ = "";
      indexdata_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
      return new BlobHeader();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private BlobHeader(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              type_ = bs;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              indexdata_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              datasize_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return crosby.binary.Fileformat.internal_static_OSMPBF_BlobHeader_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return crosby.binary.Fileformat.internal_static_OSMPBF_BlobHeader_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
          crosby.binary.Fileformat.BlobHeader.class, crosby.binary.Fileformat.BlobHeader.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;

    /**
     * <code>required string type = 1;</code>
     * 
     * @return Whether the type field is set.
     */
    @java.lang.Override
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>required string type = 1;</code>
     * 
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }

    /**
     * <code>required string type = 1;</code>
     * 
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INDEXDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString indexdata_;

    /**
     * <code>optional bytes indexdata = 2;</code>
     * 
     * @return Whether the indexdata field is set.
     */
    @java.lang.Override
    public boolean hasIndexdata() {
      return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>optional bytes indexdata = 2;</code>
     * 
     * @return The indexdata.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getIndexdata() {
      return indexdata_;
    }

    public static final int DATASIZE_FIELD_NUMBER = 3;
    private int datasize_;

    /**
     * <code>required int32 datasize = 3;</code>
     * 
     * @return Whether the datasize field is set.
     */
    @java.lang.Override
    public boolean hasDatasize() {
      return ((bitField0_ & 0x00000004) != 0);
    }

    /**
     * <code>required int32 datasize = 3;</code>
     * 
     * @return The datasize.
     */
    @java.lang.Override
    public int getDatasize() {
      return datasize_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDatasize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBytes(2, indexdata_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, datasize_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1)
        return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, indexdata_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, datasize_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof crosby.binary.Fileformat.BlobHeader)) {
        return super.equals(obj);
      }
      crosby.binary.Fileformat.BlobHeader other = (crosby.binary.Fileformat.BlobHeader) obj;

      if (hasType() != other.hasType())
        return false;
      if (hasType()) {
        if (!getType()
          .equals(other.getType()))
          return false;
      }
      if (hasIndexdata() != other.hasIndexdata())
        return false;
      if (hasIndexdata()) {
        if (!getIndexdata()
          .equals(other.getIndexdata()))
          return false;
      }
      if (hasDatasize() != other.hasDatasize())
        return false;
      if (hasDatasize()) {
        if (getDatasize() != other.getDatasize())
          return false;
      }
      if (!unknownFields.equals(other.unknownFields))
        return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      if (hasIndexdata()) {
        hash = (37 * hash) + INDEXDATA_FIELD_NUMBER;
        hash = (53 * hash) + getIndexdata().hashCode();
      }
      if (hasDatasize()) {
        hash = (37 * hash) + DATASIZE_FIELD_NUMBER;
        hash = (53 * hash) + getDatasize();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static crosby.binary.Fileformat.BlobHeader parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static crosby.binary.Fileformat.BlobHeader parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static crosby.binary.Fileformat.BlobHeader parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static crosby.binary.Fileformat.BlobHeader parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static crosby.binary.Fileformat.BlobHeader parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static crosby.binary.Fileformat.BlobHeader parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static crosby.binary.Fileformat.BlobHeader parseFrom(java.io.InputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
    }

    public static crosby.binary.Fileformat.BlobHeader parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static crosby.binary.Fileformat.BlobHeader parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
    }

    public static crosby.binary.Fileformat.BlobHeader parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static crosby.binary.Fileformat.BlobHeader parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
    }

    public static crosby.binary.Fileformat.BlobHeader parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(crosby.binary.Fileformat.BlobHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code OSMPBF.BlobHeader}
     */
    public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:OSMPBF.BlobHeader)
      crosby.binary.Fileformat.BlobHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return crosby.binary.Fileformat.internal_static_OSMPBF_BlobHeader_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return crosby.binary.Fileformat.internal_static_OSMPBF_BlobHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
            crosby.binary.Fileformat.BlobHeader.class, crosby.binary.Fileformat.BlobHeader.Builder.class);
      }

      // Construct using crosby.binary.Fileformat.BlobHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        indexdata_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        datasize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return crosby.binary.Fileformat.internal_static_OSMPBF_BlobHeader_descriptor;
      }

      @java.lang.Override
      public crosby.binary.Fileformat.BlobHeader getDefaultInstanceForType() {
        return crosby.binary.Fileformat.BlobHeader.getDefaultInstance();
      }

      @java.lang.Override
      public crosby.binary.Fileformat.BlobHeader build() {
        crosby.binary.Fileformat.BlobHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public crosby.binary.Fileformat.BlobHeader buildPartial() {
        crosby.binary.Fileformat.BlobHeader result = new crosby.binary.Fileformat.BlobHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.indexdata_ = indexdata_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.datasize_ = datasize_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof crosby.binary.Fileformat.BlobHeader) {
          return mergeFrom((crosby.binary.Fileformat.BlobHeader) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(crosby.binary.Fileformat.BlobHeader other) {
        if (other == crosby.binary.Fileformat.BlobHeader.getDefaultInstance())
          return this;
        if (other.hasType()) {
          bitField0_ |= 0x00000001;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasIndexdata()) {
          setIndexdata(other.getIndexdata());
        }
        if (other.hasDatasize()) {
          setDatasize(other.getDatasize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        if (!hasDatasize()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
        crosby.binary.Fileformat.BlobHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (crosby.binary.Fileformat.BlobHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private java.lang.Object type_ = "";

      /**
       * <code>required string type = 1;</code>
       * 
       * @return Whether the type field is set.
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) != 0);
      }

      /**
       * <code>required string type = 1;</code>
       * 
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>required string type = 1;</code>
       * 
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>required string type = 1;</code>
       * 
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
        java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required string type = 1;</code>
       * 
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }

      /**
       * <code>required string type = 1;</code>
       * 
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString indexdata_ = com.google.protobuf.ByteString.EMPTY;

      /**
       * <code>optional bytes indexdata = 2;</code>
       * 
       * @return Whether the indexdata field is set.
       */
      @java.lang.Override
      public boolean hasIndexdata() {
        return ((bitField0_ & 0x00000002) != 0);
      }

      /**
       * <code>optional bytes indexdata = 2;</code>
       * 
       * @return The indexdata.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getIndexdata() {
        return indexdata_;
      }

      /**
       * <code>optional bytes indexdata = 2;</code>
       * 
       * @param value The indexdata to set.
       * @return This builder for chaining.
       */
      public Builder setIndexdata(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        indexdata_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>optional bytes indexdata = 2;</code>
       * 
       * @return This builder for chaining.
       */
      public Builder clearIndexdata() {
        bitField0_ = (bitField0_ & ~0x00000002);
        indexdata_ = getDefaultInstance().getIndexdata();
        onChanged();
        return this;
      }

      private int datasize_;

      /**
       * <code>required int32 datasize = 3;</code>
       * 
       * @return Whether the datasize field is set.
       */
      @java.lang.Override
      public boolean hasDatasize() {
        return ((bitField0_ & 0x00000004) != 0);
      }

      /**
       * <code>required int32 datasize = 3;</code>
       * 
       * @return The datasize.
       */
      @java.lang.Override
      public int getDatasize() {
        return datasize_;
      }

      /**
       * <code>required int32 datasize = 3;</code>
       * 
       * @param value The datasize to set.
       * @return This builder for chaining.
       */
      public Builder setDatasize(int value) {
        bitField0_ |= 0x00000004;
        datasize_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>required int32 datasize = 3;</code>
       * 
       * @return This builder for chaining.
       */
      public Builder clearDatasize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        datasize_ = 0;
        onChanged();
        return this;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OSMPBF.BlobHeader)
    }

    // @@protoc_insertion_point(class_scope:OSMPBF.BlobHeader)
    private static final crosby.binary.Fileformat.BlobHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new crosby.binary.Fileformat.BlobHeader();
    }

    public static crosby.binary.Fileformat.BlobHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated
    public static final com.google.protobuf.Parser<BlobHeader> PARSER =
      new com.google.protobuf.AbstractParser<BlobHeader>() {
        @java.lang.Override
        public BlobHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BlobHeader(input, extensionRegistry);
        }
      };

    public static com.google.protobuf.Parser<BlobHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BlobHeader> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public crosby.binary.Fileformat.BlobHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor internal_static_OSMPBF_Blob_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_OSMPBF_Blob_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor internal_static_OSMPBF_BlobHeader_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_OSMPBF_BlobHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3planetiler-core/src/main/resources/fil" +
        "eformat.proto\022\006OSMPBF\"\245\001\n\004Blob\022\020\n\010raw_si" +
        "ze\030\002 \001(\005\022\r\n\003raw\030\001 \001(\014H\000\022\023\n\tzlib_data\030\003 \001" +
        "(\014H\000\022\023\n\tlzma_data\030\004 \001(\014H\000\022!\n\023OBSOLETE_bz" +
        "ip2_data\030\005 \001(\014B\002\030\001H\000\022\022\n\010lz4_data\030\006 \001(\014H\000" +
        "\022\023\n\tzstd_data\030\007 \001(\014H\000B\006\n\004data\"?\n\nBlobHea" +
        "der\022\014\n\004type\030\001 \002(\t\022\021\n\tindexdata\030\002 \001(\014\022\020\n\010" +
        "datasize\030\003 \002(\005B\017\n\rcrosby.binary"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[]{
        });
    internal_static_OSMPBF_Blob_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OSMPBF_Blob_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
      internal_static_OSMPBF_Blob_descriptor,
      new java.lang.String[]{"RawSize", "Raw", "ZlibData", "LzmaData", "OBSOLETEBzip2Data", "Lz4Data", "ZstdData",
        "Data",});
    internal_static_OSMPBF_BlobHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OSMPBF_BlobHeader_fieldAccessorTable =
      new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OSMPBF_BlobHeader_descriptor,
        new java.lang.String[]{"Type", "Indexdata", "Datasize",});
  }

  // @@protoc_insertion_point(outer_class_scope)
}
